const ADJECTIVES: [&'static str; 64] = [
    "red",
    "green",
    "blue",
    "yellow",
    "cyan",
    "magenta",
    "orange",
    "purple",
    "brown",
    "white",
    "black",
    "small",
    "tiny",
    "large",
    "huge",
    "big",
    "giant",
    "fast",
    "slow",
    "funny",
    "boring",
    "lame",
    "interesting",
    "holy",
    "scary",
    "scared",
    "hidden",
    "smart",
    "quick",
    "heavy",
    "light",
    "smooth",
    "raw",
    "hairy",
    "furry",
    "glowing",
    "loose",
    "tight",
    "metallic",
    "plastic",
    "wooden",
    "fallen",
    "ambitious",
    "clever",
    "flying",
    "brittle",
    "bright",
    "dark",
    "brave",
    "lonely",
    "free",
    "tired",
    "sleepy",
    "hungry",
    "happy",
    "sad",
    "spicy",
    "sacred",
    "burnt",
    "frozen",
    "toxic",
    "venomous",
    "curly",
    "original",
];

const NOUNS: [&'static str; 64] = [
    "mice",
    "sheep",
    "cats",
    "dogs",
    "chinchillas",
    "rats",
    "hamsters",
    "squirrels",
    "apes",
    "octopi",
    "ducks",
    "doves",
    "geese",
    "pidgeons",
    "seagulls",
    "crocodiles",
    "monkeys",
    "turtles",
    "ants",
    "bugs",
    "beetles",
    "spiders",
    "oranges",
    "apples",
    "pears",
    "grapes",
    "clementines",
    "mangos",
    "dates",
    "bananas",
    "fairies",
    "ogres",
    "goblins",
    "dwarves",
    "elves",
    "wizards",
    "warriors",
    "monks",
    "warlocks",
    "sorcerers",
    "cubes",
    "pyramids",
    "spheres",
    "squares",
    "circles",
    "stars",
    "triangles",
    "hearts",
    "lungs",
    "kidneys",
    "brains",
    "veins",
    "muscles",
    "bones",
    "joints",
    "eyes",
    "ears",
    "noses",
    "mouths",
    "intestines",
    "arms",
    "legs",
    "torsos",
    "nerves",
];

pub fn get_hrid() -> String {
    let number: u32 = (rand::random::<u8>() as u32) + 2;
    let i_adj: u32 = rand::random::<u32>() % 64;
    let i_noun: u32 = rand::random::<u32>() % 64;
    let number2: u32 = (rand::random::<u8>() as u32) + 2;
    let i_adj2: u32 = rand::random::<u32>() % 64;
    let i_noun2: u32 = rand::random::<u32>() % 64;
    format!(
        "{}-{}-{}-and-{}-{}-{}",
        number,
        ADJECTIVES[i_adj as usize],
        NOUNS[i_noun as usize],
        number2,
        ADJECTIVES[i_adj2 as usize],
        NOUNS[i_noun2 as usize],
    )
}